### ISSUE TITLE
Compile error: /usr/include doesn't match in the case of Nerves cross compiled by macOS

### ISSUE THREAD

**Issue by zacky1972** [zeam-vm/pelemay#92]
**Describe the bug**

Compile errors occur because `/usr/include` doesn't match in the case of Nerves cross compiled by macOS.

**To Reproduce**
1. `mix nerves.new hello_pelemay`
2. modify according to (https://github.com/TORIFUKUKaiou/hello_pelemay/commit/4648d033abaf8dc71791bd46757c704d50460641)
3. Use Pelemay in mix.exs 'branch: nerves_gcc' (cfe5c44b76ca34010319091b3faed488b063bf35)
4. `export MIX_TARGET=rpi4` (or another platform)
5. `mix deps.get`
6. `mix firmware`

The following errors occurs:

```
In file included from /usr/include/sys/types.h:75,
                 from /Users/zacky/kerl/22.1_clang_10.0.0_6c3f/erts-10.5/include/erl_drv_nif.h:158,
                 from /Users/zacky/kerl/22.1_clang_10.0.0_6c3f/erts-10.5/include/erl_nif.h:31,
                 from /Users/zacky/hello_pelemay/_build/rpi4_dev/lib/pelemay/priv/libnifelixirpelemaysample.c:3:
/usr/include/sys/cdefs.h:784:2: error: #error Unsupported architecture
 #error Unsupported architecture
  ^~~~~
In file included from /usr/include/sys/types.h:78,
                 from /Users/zacky/kerl/22.1_clang_10.0.0_6c3f/erts-10.5/include/erl_drv_nif.h:158,
                 from /Users/zacky/kerl/22.1_clang_10.0.0_6c3f/erts-10.5/include/erl_nif.h:31,
                 from /Users/zacky/hello_pelemay/_build/rpi4_dev/lib/pelemay/priv/libnifelixirpelemaysample.c:3:
/usr/include/machine/types.h:37:2: error: #error architecture not supported
 #error architecture not supported
  ^~~~~
In file included from /usr/include/sys/_types.h:33,
                 from /usr/include/sys/types.h:79,
                 from /Users/zacky/kerl/22.1_clang_10.0.0_6c3f/erts-10.5/include/erl_drv_nif.h:158,
                 from /Users/zacky/kerl/22.1_clang_10.0.0_6c3f/erts-10.5/include/erl_nif.h:31,
                 from /Users/zacky/hello_pelemay/_build/rpi4_dev/lib/pelemay/priv/libnifelixirpelemaysample.c:3:
/usr/include/machine/_types.h:34:2: error: #error architecture not supported
 #error architecture not supported
  ^~~~~
In file included from /usr/include/sys/types.h:79,
                 from /Users/zacky/kerl/22.1_clang_10.0.0_6c3f/erts-10.5/include/erl_drv_nif.h:158,
                 from /Users/zacky/kerl/22.1_clang_10.0.0_6c3f/erts-10.5/include/erl_nif.h:31,
                 from /Users/zacky/hello_pelemay/_build/rpi4_dev/lib/pelemay/priv/libnifelixirpelemaysample.c:3:
/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'
 typedef __int64_t       __darwin_blkcnt_t;      /* total blocks */
         ^~~~~~~~~
/usr/include/sys/_types.h:56:9: error: unknown type name '__int32_t'
 typedef __int32_t       __darwin_blksize_t;     /* preferred block size */
         ^~~~~~~~~
/usr/include/sys/_types.h:57:9: error: unknown type name '__int32_t'
 typedef __int32_t       __darwin_dev_t;         /* dev_t */
         ^~~~~~~~~
/usr/include/sys/_types.h:60:9: error: unknown type name '__uint32_t'
 typedef __uint32_t      __darwin_gid_t;         /* [???] process and group IDs */
         ^~~~~~~~~~
/usr/include/sys/_types.h:61:9: error: unknown type name '__uint32_t'
 typedef __uint32_t      __darwin_id_t;          /* [XSI] pid_t, uid_t, or gid_t*/
[snipped]
```

This is because of mismatch of `/use/include`

**Expected behavior**
No error occurs.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - Pelemay Version: 'branch: nerves gcc' (cfe5c44b76ca34010319091b3faed488b063bf35)
 - Elixir & Erlang/OTP versions (`elixir --version`): 1.9.4 / 22
 - OS (OS name & version, and `uname -a`):  macOS
 - Clang versions (`clang -v`): N/A

**Additional context**
None.

**Comment by fhunleth** [comment]
Nerves uses environment variables to pass information about the C compiler and the locations of include files and libraries.

It sounds like you need `$CC` and `$CFLAGS` to get the crosscompiler and compile flags. Then after that, I think that you'll need `$ERL_CFLAGS` and `$ERL_LDFLAGS` to get the paths to the Erlang include directory and library for the version of Erlang running on the target.

Here's an example Makefile that handles being called using Nerves and not using Nerves:

https://github.com/elixir-circuits/circuits_i2c/blob/master/Makefile

The main note on that Makefile is that some environment variables come from mix and some from Nerves. `elixir_make` defines `$ERL_EI_INCLUDE_DIR` and `$ERL_EI_LIB_DIR` (see https://hexdocs.pm/elixir_make/Mix.Tasks.Compile.ElixirMake.html#module-default-environment-variables). When using Nerves, the Makefile ignores those since those will be for the host. `$ERL_CFLAGS` and `$ERL_LDFLAGS` are set for the target. When not using Nerves, though, the Makefile constructs `$ERL_CFLAGS` and `$ERL_LDFLAGS`, though.

**Comment by zacky1972** [comment]
Thank you very much!
